name: reviewdog
on:
  pull_request:
    branches: [ "main" ]

jobs:
  checkstyle:
    name: checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dbelyaev/action-checkstyle@master
        with:
          github_token: "${{ secrets.TOKEN }}"
          reporter: github-pr-review
          checkstyle_config: sun_checks.xml
          level: warning
